spring.datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: password
  generate-unique-name: false
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.h2.console:
  enabled: true
  path: /h2-console
  settings.trace: false
  settings.web-allow-others: false

app.met.url: https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=%s&lon=%s